name: '🏃 Sprint Backlog Item (SBI)'
description: 'Add a new SBI to a sprint.'
#labels: []
#projects: ["sendance/4"]
#assignees:

body:
- type: markdown
  attributes:
    value: "To expedite issue processing, please search open and closed issues before submitting a new one. Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`"
- type: markdown
  attributes:
    value: "# 🏃 SBI"
- type: textarea
  attributes:
    label: Goal
    description: Provide a concise description what is the goal of the maximum of 3-days long SBI.
    placeholder: "e.g., 'Improved documentation README of how to use RTT'"
  validations:
    required: false
- type: textarea
  attributes:
    label: Results
    description: |
      Outline the results achieved and/or link to further documentation or git-commits/PRs/branches.     
    placeholder: |
      e.g., Tested sensor basis x and y. X had 30% less offset on average. More docs see Google Drive: <link> 
  validations:
    required: false
- type: textarea
  attributes:
    label: Execution
    description: |
      Add a list of (to-be- or already ) executed steps.    
    placeholder: |
      e.g., Tasks: 1. Researched sensor basis options, 2. Order 2 most favorable ones 3. Build & test 2 samples  4. Evaluate data 5. Write documentation
  validations:
    required: false
