name: '🚀🆕 Feature Request'
description: 'Suggest a new feature for this project.'
title: '[Feature] '
#labels: ['Topic: Feature', 'Status: In Triage']
#projects: ["sendance/4"]
#assignees:

body:
- type: markdown
  attributes:
    value: "To expedite issue processing, please search open and closed issues before submitting a new one. Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`"
- type: markdown
  attributes:
    value: "# 🚀🆕 Feature Request"
- type: input
  attributes:
    label: Source Type
    description: Where the this issue/request originates from. E.g. a backlog ticket, QMS-Ticket (PIT) or Customer Feedback, Ideation Workshop Meeting, etc.
    placeholder: "e.g. 'Backlog'"
  validations:
    required: false
- type: input
  attributes:
    label: Source Link
    description: E.g. a link to the backlog ticket, customer support request, meeting notes etc.
    placeholder: "E.g. '#xyz' or 'https//...'"
  validations:
    required: false
- type: textarea
  attributes:
    label: Description
    description: Provide a clear and concise description of the feature you are requesting ('what do I want?').
    placeholder: "E.g. Ability to download local IMU recordings"
  validations:
    required: false
- type: textarea
  attributes:
    label: Problem Statement
    description: |
      Explain the problem or pain point that this feature would address ('why do I want it?'). Provide context and examples to help others understand the need for this feature. 
    placeholder: "E.g. currently we can record IMU data but have no option to download it"
  validations:
    required: false
- type: textarea
  attributes:
    label: Proposed Solution
    description: Describe your proposed solution or idea for implementing the feature. Include any relevant details, functionality, or benefits that the feature would provide.
    placeholder: "E.g. introduce a BLE Action Parameter that allows to specify the type of recording data"
  validations:
    required: false
- type: textarea
  attributes:
    label: Alternatives Considered
    description: If you have considered any alternative approaches or solutions, mention them here and provide reasons why you believe your proposed solution is the most suitable.
    placeholder: "E.g. always download all available recordings sequentially"
  validations:
    required: false
- type: textarea
  attributes:
    label: Media
    description: If applicable, include screenshots or GIFs to help understanding how the feature should look like (e.g. design draft, screenshots) or how it should work (e.g. flow diagram).
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: Include any additional information or context that might be helpful for reviewers or developers.
    placeholder: "e.g. We already tested downloading recordings sequentially successfully, but in the future, this could mean really long downloading times."
  validations:
    required: false
- type: markdown
  attributes:
    value: "_The following sections have to be filled by the person who is responsible for solving the bug._"
- type: textarea
  attributes:
    label: Solution Summary
    description: (TO BE FILLED BY ENGINEER)
    placeholder: Provide a brief summary of the final decision and, if applicable, of the final solution and its outcome.
  validations:
    required: false
- type: textarea
  attributes:
    label: Solution Path
    description: (TO BE FILLED BY ENGINEER)
    placeholder: As engineer, after creating the PBI, use the `Create sub-issue / Add existing issue` feature to add your new/planned/already defined SBIs.
  validations:
    required: false
- type: checkboxes
  id: productcataloguecb
  attributes:
    label: Product Catalogue Updated
    description: (To be filled before finishing/closing/completing this ticket)
    options:
      - label: I have updated an existing or added a new item to the product catalogue to reflect the change(s) implemented in this PBI.
        required: false
      - label: It's not necessary to update the product catalogue due to this PBI.
        required: false