name: '🚀🌟 Enhancement Request'
description: 'Suggest an enhancement for this project.'
title: '[Enhancement] '
#labels: ['Topic: Enhancement', 'Status: In Triage']
#projects: ["sendance/4"]
#assignees:

body:
- type: markdown
  attributes:
    value: "To expedite issue processing, please search open and closed issues before submitting a new one. Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`"
- type: markdown
  attributes:
    value: "# 🚀🆕 Enhancement Request"
- type: input
  attributes:
    label: Source Type
    description: Where the this issue/request originates from. E.g. a backlog ticket, QMS-Ticket (PIT) or Customer Feedback, Ideation Workshop Meeting, etc.
    placeholder: "e.g. 'Backlog'"
  validations:
    required: false
- type: input
  attributes:
    label: Source Link
    description: E.g. a link to the backlog ticket, customer support request, meeting notes etc.
    placeholder: "E.g. '#xyz' or 'https//...'"
  validations:
    required: false
- type: textarea
  attributes:
    label: Description
    description: Provide a clear and concise description of the enhancement you are requesting.
  validations:
    required: false
- type: textarea
  attributes:
    label: Problem Statement
    description: |
      Explain the problem or limitation that this enhancement would address. Provide context and examples to help others understand the need for this enhancement.
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Functionality
    description:  Describe the current functionality or feature that the enhancement would build upon or improve. Explain any specific areas or aspects that you believe can be enhanced.
  validations:
    required: false
- type: textarea
  attributes:
    label: Proposed Enhancement
    description:  Describe your proposed enhancement in detail. Include any specific features, improvements, or changes that you would like to see. Provide examples or use cases to illustrate how the enhancement would benefit users.
  validations:
    required: false
- type: textarea
  attributes:
    label: Alternatives Considered
    description: If you have considered any alternative approaches or solutions, mention them here and provide reasons why you believe your proposed enhancement is the most suitable.
  validations:
    required: false
- type: textarea
  attributes:
    label: Media
    description: If applicable, include screenshots or GIFs to help understanding how the enhancement should look like (e.g. design draft, screenshots) or how it should work (e.g. flow diagram).
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: Include any additional information or context that might be helpful for reviewers or developers.
  validations:
    required: false
- type: markdown
  attributes:
    value: "_The following sections have to be filled by the person who is responsible for solving the bug._"
- type: textarea
  attributes:
    label: Solution Summary
    description: (TO BE FILLED BY ENGINEER)
    placeholder: Provide a brief summary of the final decision and, if applicable, of the final solution and its outcome.
  validations:
    required: false
- type: textarea
  attributes:
    label: Solution Path
    description: (TO BE FILLED BY ENGINEER)
    placeholder: As engineer, after creating the PBI, use the `Create sub-issue / Add existing issue` feature to add your new/planned/already defined SBIs.
  validations:
    required: false
- type: checkboxes
  id: productcataloguecb
  attributes:
    label: Product Catalogue Updated
    description: (To be filled before finishing/closing/completing this ticket)
    options:
      - label: I have updated an existing or added a new item to the product catalogue to reflect the change(s) implemented in this PBI.
        required: false
      - label: It's not necessary to update the product catalogue due to this PBI.
        required: false